#!/bin/sh /etc/rc.common

START=11
STOP=15

SCRIPT="/bin/nebula -config /etc/nebula/config.yml"

PIDFILE=/var/run/nebula.pid
LOGFILE=/var/log/nebula.log

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting nebula service…' >&2
  $SCRIPT &> "$LOGFILE" & echo $! > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping nebula service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}
